spring.application.name=avalon
server.port=${PORT:8900}

# Local PostgreSQL Configuration (AV_CORE_2)
# spring.datasource.url=jdbc:postgresql://localhost:9800/AvalonApi
# spring.datasource.username=SoporteAvalonFrias
# spring.datasource.password=frias

# Cloud PostgreSQL Configuration (Render / Railway)
spring.datasource.url=jdbc:postgresql://dpg-daa7engn74is73a2ne80-a.oregon-postgres.render.com:5432/bdavalonplaza
spring.datasource.username=bdavalonplaza_user
spring.datasource.password=MkBnK2IvNChQYpmHI9b4deflupoTMnTI


# postgresql://bdavalonplaza_user:MkBnK2IvNChQYpmHI9b4deflupoTMnTI@dpg-daa7engn74is73a2ne80-a/bdavalonplaza
# Flyway toma el control
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/global
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.baseline-description=Initial Schema Baseline
spring.flyway.out-of-order=true
spring.flyway.repair-on-migrate=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.leak-detection-threshold=3000
spring.datasource.hikari.pool-name=AvalonHikariPool

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# =================================
# EXTERNAL SERVICES & SECRETS
# =================================
aws.accessKey=${AWS_ACCESS_KEY:}
aws.secretKey=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:us-east-2}

removebg.apikey=${REMOVE_BG_KEY:}

#config clave secreta
app.jwt.secret=${JWT_SECRET_KEY:XctaoGR8Dk8Pp7wWb27xsLsnkEmHEVd0cXn4z9xZy8k=}
app.jwt.expiration-ms=${JWT_EXPIRATION_TIME_MS:900000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_TIME_MS:2592000000}

# App Config - Leido desde .env
app.reset-password.url=${APP_RESET_PASSWORD_URL:http://localhost:3000/reset-password}

# =================================
# SPRING AOP CONFIG
# =================================
# Fuerza a Spring a usar CGLIB para que los Aspectos capturen metodos heredados
spring.aop.proxy-target-class=true
# Asegura que la propagacion de aspectos este activa
spring.aop.auto=true

# =================================
# EMAIL (SMTP) CONFIG
# =================================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Registrar en consola cada peticion HTTP que entra a la API
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.buffered=false
server.tomcat.accesslog.suffix=

# =================================
# BREVO EMAIL API CONFIG
# =================================
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL:friastto@gmail.com}
brevo.sender.name=${BREVO_SENDER_NAME:Avalon App}
