spring.application.name=avalon
server.port=8900

#- spring.datasource.url=jdbc:postgresql://dpg-d3oicommcj7s73f02ng0-a.oregon-postgres.render.com:5432/friasappap
#- spring.datasource.userName=soportedb
#- spring.datasource.password=Ryv0jdRgpyIgfGcLO96MbAc9WTFinYon

#config posgres local
spring.datasource.url=jdbc:postgresql://localhost:9800/AvalonApi
spring.datasource.username=SoporteAvalonFrias
spring.datasource.password=frias

# Flyway toma el control
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

# =================================
# EXTERNAL SERVICES & SECRETS
# =================================
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}

removebg.apikey=${REMOVE_BG_KEY}

#config clave secreta
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration-ms=${JWT_EXPIRATION_TIME_MS}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_TIME_MS}

# App Config - Leído desde .env
app.reset-password.url=${APP_RESET_PASSWORD_URL}

# =================================
# SPRING AOP CONFIG
# =================================
# Fuerza a Spring a usar CGLIB para que los Aspectos capturen métodos heredados
spring.aop.proxy-target-class=true
# Asegura que la propagación de aspectos esté activa
spring.aop.auto=true

# =================================
# EMAIL (SMTP) CONFIG
# =================================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
